### ISSUE TITLE
Mediatek mt7922 not working probably

### ISSUE THREAD

**Issue by Spirit2113** [CachyOS/linux-cachyos#499]
i own an Asus Laptop with an Mediatek  mt7922 and at the beginning the controller is working probably but than it slows down and stops working with my avm fritzbox 7590 wlan network but works with my hotspot from my pixel 7 pro.

but that's only on cachyos.
under bazzite, nobara, pop_os its working correct.

**Comment by 1Naim** [comment]
Nobara's patches are basically 1:1 with us because they source it from ours, with the addition of some other patches. CachyOS doesn't make any changes to the MediaTek stack, nor any of the other wireless stack for that matter and I don't believe Nobara does too. 

I think the problem here is in the firmware. What version of `linux-firmware` are you on?

**Comment by Spirit2113** [comment]
Have to reinstall it.
Last install was 5-8 weeks ago and I always do updates with pacman -Syu, so I think the newest.
And I'm not the only person with this failure, there are plenty in discord from cachyos.

**Comment by 1Naim** [comment]
The easiest way to check if it's an issue with out patches or not is by cross checking with the `linux` kernel package. Can you please do that?

**Comment by ptr1337** [comment]
Its likely an linux-firmware issue due having a newer firmware, but the best would be if you provide logs with "sudo cachyos-bugreport.sh"

**Comment by Spirit2113** [comment]
@ptr1337 
with firtzbox
https://paste.cachyos.org/p/3353a7c.log
with pixel
https://paste.cachyos.org/p/e592490.log

since the last update its more stable but the download speed is vary pretty much.
the hotspot i provide with my pixel 7 pro is using the same wifi as in these logs and is more stable.

@1Naim 
i will switch later to the standart Linux kernel and test it

with standart kernel (linux)
https://paste.cachyos.org/p/c3de158.log

**Comment by 1Naim** [comment]
> with standart kernel (linux)
> https://paste.cachyos.org/p/c3de158.log

Is it fine or not? I honestly can't tell anything from these logs, other than maybe trying to `sudo ufw disable` (disable the firewall) if it's not. Additionally, if it is indeed the same then it's either an issue with the upstream kernel or as i said earlier, firmware, both of which we can't really do anything about.

**Comment by Spirit2113** [comment]
unfortunately not
did it also test with iwd but than my 2,4ghz wlan isnt showing and the its get no ip-address from the 5ghz network like with wpa_supplicant

**Comment by 1Naim** [comment]
> unfortunately not

Then I believe you should report this upstream.

> under bazzite, nobara, pop_os its working correct

When did you test this? Was it an older version compared to CachyOS? AFAIK PopOS is severely outdated.

**Comment by bidzapfc** [comment]
I dont wanna be bearer of bad news, but I got same mediatek junk, and it is acting weird to say at least. It is really picky when it comes to 5ghz wifis, and I will be replacing it with ax211 or realtek. This issue is almost not detectable, and it seems some firmware is forcing it to suspend. It happens on windows and linux alike. Best I could do is source a script to reup my connection whenever i couldnt ping google.

**Comment by darkhatcher17** [comment]
I also have similar issue. I have realtek card and I lose internet and then it shows no available network and sometime it hangs. Sometimes rebooting helps sometimes there is no wifi card.

https://github.com/CachyOS/distribution/issues/205

**Comment by ptr1337** [comment]
Is this still an issue?

**Comment by joaorsbarbosa** [comment]
Have the same Wi-FI card and 6 Ghz is just completely broken :(

**Comment by ptr1337** [comment]
> Have the same Wi-FI card and 6 Ghz is just completely broken :(

Report it to Mediatek or bugzilla.kernel.org

**Comment by joaorsbarbosa** [comment]
> > Have the same Wi-FI card and 6 Ghz is just completely broken :(
> 
> Report it to Mediatek or bugzilla.kernel.org

I believe someone already has. I _think_ this bug report is relevant, but as a newbie I'm not sure 
https://bugzilla.redhat.com/show_bug.cgi?id=2411854

Edit: just saw it's at redhat.com and not kernel.org

**Comment by darkhatcher17** [comment]
Sorry for the very late reply. Mine had the issue which was fixed mostly by taking the wifi card out and then reseating it. It was later on completely fixed by 6.17 kernel.

**Comment by joaorsbarbosa** [comment]
> Sorry for the very late reply. Mine had the issue which was fixed mostly by taking the wifi card out and then reseating it. It was later on completely fixed by 6.17 kernel.

Curious. Using the latest CachyOS version I still have issues connecting to certain networks (WPA3/6 GHz) whislt it's rock solid on windows. Making a Ubuntu live USB as we speak to test it there

**Comment by joaorsbarbosa** [comment]
> > Sorry for the very late reply. Mine had the issue which was fixed mostly by taking the wifi card out and then reseating it. It was later on completely fixed by 6.17 kernel.
> 
> Curious. Using the latest CachyOS version I still have issues connecting to certain networks (WPA3/6 GHz) whislt it's rock solid on windows. Making a Ubuntu live USB as we speak to test it there

Didn't work in Ubuntu but Wi-Fi on the MT7922 is working perfectly with Fedora 43 KDE
