### ISSUE TITLE
Contradictory information - repo readme vs Wiki

### ISSUE THREAD

**Issue by spinktvis** [CachyOS/linux-cachyos#530]
There's contradictory information on the Wiki vs repo, this not only applies to the kernel info part and the readme located here, but for example the Wiki gaming section (the Wine part) as well, for which there are a couple of tickets already located and found here https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/779
https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/800

Anyway, back to this, a small example, the Wiki https://wiki.cachyos.org/features/kernel/#why-is-autofdo-not-being-used-for-all-the-other-kernel-variants says only the default linux-cachyos kernel is compiled with FDO vs the info found here in the readme https://github.com/CachyOS/linux-cachyos#compiler-variants which indicates that only linux-cachyos-lto - Clang and Thin LTO, utilizing AutoFDO + Propeller profiling for optimal performance is the only one that has FDO.

So what is the truth? Which kernel is actually compiled with FDO? 

I must admit that such contradictory information is confusing for new users, especially if one follows Phoronix and reads that FDO + Propellor has been disabled entirely a while back due to the then ongoing issues (not sure how relevant that part still is).

Hopefully the communication between the maintainers and editors of the wiki can be further improved upon to avoid such things, since other than that CachyOS does a lot right the first time!

**Comment by Aarrayy** [comment]
<img width="268" height="200" alt="Image" src="https://github.com/user-attachments/assets/21067e37-66bc-43ec-910d-af9fd35a98c2" />

**Comment by ptr1337** [comment]
The default LTO got reverted due a bug in the NVIDIA Driver and not bootable Systems. This has been fixed in the 580 beta series, as soon this one goes stable we will provide again Clang and AutoFdo/Propeller built kernels

**Comment by spinktvis** [comment]
How has this been completed since the wiki vs repo readme still shows the same contradictory information?

Also, what would be recommended for AMD GPU users? To always use the LTO variant? Such information might be handy.
