### ISSUE TITLE
Can't compile 6.1.4

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/linux-cachyos#55]
Tried a variety of configurations, but always get this error:
```
ERROR: modpost: "__get_random_u32_below" [fs/ext4/ext4.ko] undefined!
ERROR: modpost: "__get_random_u32_below" [net/netfilter/nf_nat.ko] undefined!
ERROR: modpost: "__get_random_u32_below" [net/bluetooth/bluetooth.ko] undefined!
ERROR: modpost: "__get_random_u32_below" [net/sunrpc/sunrpc.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
make: *** [Makefile:1942: modpost] Error 2
```

**Comment by ptr1337** [comment]
> Tried a variety of configurations, but always get this error:
> 
> ```
> ERROR: modpost: "__get_random_u32_below" [fs/ext4/ext4.ko] undefined!
> ERROR: modpost: "__get_random_u32_below" [net/netfilter/nf_nat.ko] undefined!
> ERROR: modpost: "__get_random_u32_below" [net/bluetooth/bluetooth.ko] undefined!
> ERROR: modpost: "__get_random_u32_below" [net/sunrpc/sunrpc.ko] undefined!
> make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
> make: *** [Makefile:1942: modpost] Error 2
> ```

Hey!

This is fixed with the latest push I sent. This happened due a ABI change in the random code.
I will push the AUR packages now.

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/commit/106dc2d238dbc80551a04332bb43960b0d7e977f

https://github.com/CachyOS/kernel-patches/commit/9b36d8fdd1b47ee677822220df69b7b886294062

Got fixed with these commits

**Comment by xuanruiqi** [comment]
Thanks!

**Comment by Hebarch** [comment]
I still can't compile 6.1.4, even with the new commit applied. :-(

```
ERROR: modpost: "__get_random_u32_below" [fs/ext4/ext4.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
make: *** [Makefile:1945: modpost] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by sirlucjan** [comment]
Please disable LRNG. Seems to be broken at the moment.

**Comment by ptr1337** [comment]
> I still can't compile 6.1.4, even with the new commit applied. :-(
> 
> ```
> ERROR: modpost: "__get_random_u32_below" [fs/ext4/ext4.ko] undefined!
> make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
> make: *** [Makefile:1945: modpost] Error 2
> ==> ERROR: A failure occurred in build().
> ```

Im going to check it later. We dont have LRNG enabled as default anymore, reason why the builds on the server went without problems.
This is related to:
https://github.com/smuellerDD/lrng/issues/25

Im going to test this later.

**Comment by sirlucjan** [comment]
@ptr1337 @Hebarch @xuanruiqi 

I've updated lrng-6.1 branch: https://github.com/CachyOS/linux/compare/07cf237c5fd0...4681b0d5c9fb

Could you check?

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/commit/b9ac89aa25cffb39db709228d51e242e177f8f05

Should be solved now. Repull the patch please :)

**Comment by Hebarch** [comment]
I forgot to mention, i was not using the LRNG patchset, early tonight i have tried to compile 6.1.4 and compilation failed after trying to create vmlinux img.

```
ld.lld: error: undefined symbol: epp_values
>>> referenced by ld-temp.o
>>>               vmlinux.o:(intel_pstate_init)
>>> referenced by ld-temp.o
>>>               vmlinux.o:(intel_pstate_hwp_enable)
>>> referenced by ld-temp.o
>>>               vmlinux.o:(intel_pstate_hwp_enable)
>>> referenced 6 more times

ld.lld: error: undefined symbol: energy_perf_strings
>>> referenced by ld-temp.o
>>>               vmlinux.o:(show_energy_performance_available_preferences)
>>> referenced by ld-temp.o
>>>               vmlinux.o:(show_energy_performance_available_preferences)
>>> referenced by ld-temp.o
>>>               vmlinux.o:(show_energy_performance_preference)
>>> referenced 1 more times
make[1]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
make: *** [Makefile:1237: vmlinux] Error 2
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```
Maybe it's an upstream issue ? (LRNG is turned off, and the compilation still failing)

**Comment by ptr1337** [comment]
> @ptr1337 @sirlucjan I forgot to mention, i was not using the LRNG patchset, early tonight i have tried to compile 6.1.4 and compilation failed after trying to create vmlinux img.
> 
> ```
> ld.lld: error: undefined symbol: epp_values
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(intel_pstate_init)
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(intel_pstate_hwp_enable)
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(intel_pstate_hwp_enable)
> >>> referenced 6 more times
> 
> ld.lld: error: undefined symbol: energy_perf_strings
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(show_energy_performance_available_preferences)
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(show_energy_performance_available_preferences)
> >>> referenced by ld-temp.o
> >>>               vmlinux.o:(show_energy_performance_preference)
> >>> referenced 1 more times
> make[1]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
> make: *** [Makefile:1237: vmlinux] Error 2
> make: *** Waiting for unfinished jobs....
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```
> 
> Maybe it's an upstream issue ? (LRNG is turned off, and the compilation still failing)

This seems to me like a issue with the new amd-pstate-epp driver.
Do you have your config stripped or using modprobed-db?

On our server all builds with gcc and llvm thin lto went through.
Can you maybe share the settings you set in the PKGBUILD and your used config?

**Comment by Hebarch** [comment]
Hey @ptr1337, you're right about amd-pstate-epp driver and yes, i use modprobed-db, i forgot to enable CONFIG_X86_AMD_PSTATE on my config and now my kernel compiles normally, tysm =D.

But one more question, 6.1.4 forward, i need to explicity enable this option ? (since i don't have an AMD CPU)

**Comment by ptr1337** [comment]
> Hey @ptr1337, you're right about amd-pstate-epp driver and yes, i use modprobed-db, i forgot to enable CONFIG_X86_AMD_PSTATE on my config and now my kernel compiles normally, tysm =D.
> 
> But one more question, 6.1.4 forward, i need to explicity enable this option ? (since i don't have an AMD CPU)

Actually this issue should be reported to the maintainer.
It seems he has removed the patch, which fixed this first in the new version. This is really weird.
Here you can see the changes:
https://github.com/CachyOS/kernel-patches/commit/eb1391a1abf333eb6b99ccbd0816961258351b39#diff-6374a50fa7bd05648aa4827ad7c926cb9b2e0d7b31b09760de8a1549d59ded94L423

For 6.1.4 please keep it enabled. With 6.1.5 I hope it will be fixed.

**Comment by xuanruiqi** [comment]
Works for me! Now up and running with latest patch, thanks!

**Comment by ptr1337** [comment]
I think all issues are solved, besides the amd-pstate-epp KConfig one.
I did wrote the maintainer a mail about the issue.

Thanks for reporting, going to close here. Feel free to reopen it
